spring:
  datasource:
    url: jdbc:sqlite:clientdb.sqlite # ???? ?? ????? ???? ?????
    driver-class-name: org.sqlite.JDBC
    username: # ?? ???????? ??? SQLite
    password: # ?? ???????? ??? SQLite
  jpa:
    hibernate:
      ddl-auto: update # ??????????? ????????? ????? ???? ?????
    properties:
      hibernate:
        dialect: com.github.gwenn.sqlite.dialect.SQLiteDialect # ?????????????? ??????? SQLite